//! Thin wrapper over a 2D GPU texture + view, with an RGBA8 upload helper and
//! GPU mip-chain generation.

use anyhow::Result;

use crate::context::GpuContext;
use crate::offscreen::{read_texture_rgba8, Readback};

/// A GPU texture plus its default view (which spans every mip level).
pub struct GpuTexture {
    pub texture: wgpu::Texture,
    pub view: wgpu::TextureView,
    pub width: u32,
    pub height: u32,
    /// Number of mip levels actually allocated and written. `1` means the
    /// texture has no mip chain, and a sampler asking for mipmap filtering will
    /// silently fall back to level 0 (i.e. it will alias when minified).
    pub mip_level_count: u32,
}

impl GpuTexture {
    /// Number of mip levels a `width` x `height` texture needs to reach 1x1.
    ///
    /// Always at least 1. `mip_level_count(0, 0) == 1`.
    pub fn mip_level_count_for(width: u32, height: u32) -> u32 {
        let max = width.max(height).max(1);
        32 - max.leading_zeros()
    }

    /// Create an sRGB RGBA8 texture with a full mip chain and upload `rgba8`
    /// (row-major, `width * height * 4` bytes) into level 0.
    ///
    /// `rgba8` must be straight (non-premultiplied) alpha, which is what the
    /// canvas shader assumes when it composites over the checkerboard.
    pub fn from_rgba8(
        gpu: &GpuContext,
        width: u32,
        height: u32,
        rgba8: &[u8],
        label: &str,
    ) -> Self {
        Self::from_rgba8_with(
            gpu,
            width,
            height,
            rgba8,
            wgpu::TextureFormat::Rgba8UnormSrgb,
            true,
            label,
        )
    }

    /// Like [`GpuTexture::from_rgba8`], but with an explicit 4-byte RGBA8
    /// `format` and control over mip generation.
    ///
    /// `format` must be an RGBA8 format (`rgba8`'s row stride is computed as
    /// `4 * width`). Set `generate_mipmaps` to `false` for textures that are
    /// only ever sampled 1:1 or used as a compositing scratch buffer; it costs
    /// one render pass per level and adds `RENDER_ATTACHMENT` usage.
    pub fn from_rgba8_with(
        gpu: &GpuContext,
        width: u32,
        height: u32,
        rgba8: &[u8],
        format: wgpu::TextureFormat,
        generate_mipmaps: bool,
        label: &str,
    ) -> Self {
        assert!(width > 0 && height > 0, "{label}: zero-sized texture");
        assert_eq!(
            rgba8.len(),
            (width as usize) * (height as usize) * 4,
            "{label}: pixel buffer is not width*height*4"
        );

        let mip_level_count = if generate_mipmaps {
            Self::mip_level_count_for(width, height)
        } else {
            1
        };
        let size = wgpu::Extent3d {
            width,
            height,
            depth_or_array_layers: 1,
        };
        let mut usage = wgpu::TextureUsages::TEXTURE_BINDING
            | wgpu::TextureUsages::COPY_DST
            // So any level can be pulled back with `read_level` (export,
            // thumbnails, golden-image tests). Costs nothing at upload time.
            | wgpu::TextureUsages::COPY_SRC;
        if mip_level_count > 1 {
            usage |= wgpu::TextureUsages::RENDER_ATTACHMENT;
        }
        let texture = gpu.device.create_texture(&wgpu::TextureDescriptor {
            label: Some(label),
            size,
            mip_level_count,
            sample_count: 1,
            dimension: wgpu::TextureDimension::D2,
            format,
            usage,
            view_formats: &[],
        });

        gpu.queue.write_texture(
            wgpu::ImageCopyTexture {
                texture: &texture,
                mip_level: 0,
                origin: wgpu::Origin3d::ZERO,
                aspect: wgpu::TextureAspect::All,
            },
            rgba8,
            wgpu::ImageDataLayout {
                offset: 0,
                bytes_per_row: Some(4 * width),
                rows_per_image: Some(height),
            },
            size,
        );

        if mip_level_count > 1 {
            // Cached per (device, format): building the pipeline here would
            // recompile `mipmap.wgsl` on every single image open.
            gpu.mip_generator(format)
                .generate(gpu, &texture, mip_level_count);
        }

        let view = texture.create_view(&wgpu::TextureViewDescriptor::default());
        Self {
            texture,
            view,
            width,
            height,
            mip_level_count,
        }
    }

    /// Copy mip `level` back to CPU memory as tightly packed RGBA8.
    ///
    /// Level `n` measures `max(1, width >> n)` x `max(1, height >> n)`. Blocks
    /// until the GPU is idle, so a chain generated by [`MipGenerator`] is
    /// already complete when this returns.
    ///
    /// Errors when `level` is outside the chain or the texture's format is not
    /// an 8-bit RGBA/BGRA one.
    pub fn read_level(&self, gpu: &GpuContext, level: u32) -> Result<Readback> {
        read_texture_rgba8(gpu, &self.texture, level)
    }
}

/// Fills mip levels 1..N of a texture by repeatedly box-downsampling the level
/// above, premultiplying each tap so straight-alpha images do not darken.
///
/// The pipeline is tied to one texture format, and building it compiles
/// `mipmap.wgsl`. Do not construct one per image: call
/// [`GpuContext::mip_generator`], which caches an instance per format on the
/// context. [`MipGenerator::new`] stays public only so callers that want to own
/// the pipeline outright (or to force a compile error to surface early, as the
/// shader-validation test does) can.
pub struct MipGenerator {
    pipeline: wgpu::RenderPipeline,
    bind_group_layout: wgpu::BindGroupLayout,
}

impl MipGenerator {
    /// Build the downsample pipeline. `format` must be renderable (every
    /// `Rgba8Unorm`/`Rgba8UnormSrgb` texture is).
    ///
    /// Prefer [`GpuContext::mip_generator`] to reuse a cached instance.
    pub fn new(gpu: &GpuContext, format: wgpu::TextureFormat) -> Self {
        let shader = gpu
            .device
            .create_shader_module(wgpu::ShaderModuleDescriptor {
                label: Some("mipmap-shader"),
                source: wgpu::ShaderSource::Wgsl(render_shaders::MIPMAP_WGSL.into()),
            });

        let bind_group_layout =
            gpu.device
                .create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
                    label: Some("mipmap-bgl"),
                    // No sampler: the shader takes explicit `textureLoad` taps
                    // so it can premultiply before averaging.
                    entries: &[wgpu::BindGroupLayoutEntry {
                        binding: 0,
                        visibility: wgpu::ShaderStages::FRAGMENT,
                        ty: wgpu::BindingType::Texture {
                            sample_type: wgpu::TextureSampleType::Float { filterable: true },
                            view_dimension: wgpu::TextureViewDimension::D2,
                            multisampled: false,
                        },
                        count: None,
                    }],
                });

        let layout = gpu
            .device
            .create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
                label: Some("mipmap-pl"),
                bind_group_layouts: &[&bind_group_layout],
                push_constant_ranges: &[],
            });

        let pipeline = gpu
            .device
            .create_render_pipeline(&wgpu::RenderPipelineDescriptor {
                label: Some("mipmap-pipeline"),
                layout: Some(&layout),
                vertex: wgpu::VertexState {
                    module: &shader,
                    entry_point: "vs_main",
                    buffers: &[],
                    compilation_options: Default::default(),
                },
                fragment: Some(wgpu::FragmentState {
                    module: &shader,
                    entry_point: "fs_main",
                    targets: &[Some(wgpu::ColorTargetState {
                        format,
                        blend: None,
                        write_mask: wgpu::ColorWrites::ALL,
                    })],
                    compilation_options: Default::default(),
                }),
                primitive: wgpu::PrimitiveState::default(),
                depth_stencil: None,
                multisample: wgpu::MultisampleState::default(),
                multiview: None,
                cache: None,
            });

        Self {
            pipeline,
            bind_group_layout,
        }
    }

    /// Write levels `1..mip_level_count` of `texture`. Level 0 must already
    /// hold the source image, and the texture must carry `RENDER_ATTACHMENT`.
    ///
    /// Submits its own command buffer, so the chain is complete when this
    /// returns from the queue's point of view.
    pub fn generate(&self, gpu: &GpuContext, texture: &wgpu::Texture, mip_level_count: u32) {
        if mip_level_count < 2 {
            return;
        }
        let views: Vec<wgpu::TextureView> = (0..mip_level_count)
            .map(|level| {
                texture.create_view(&wgpu::TextureViewDescriptor {
                    label: Some("mip-level"),
                    base_mip_level: level,
                    mip_level_count: Some(1),
                    ..Default::default()
                })
            })
            .collect();

        let mut encoder = gpu
            .device
            .create_command_encoder(&wgpu::CommandEncoderDescriptor {
                label: Some("mipmap-encoder"),
            });
        for level in 1..mip_level_count as usize {
            let bind_group = gpu.device.create_bind_group(&wgpu::BindGroupDescriptor {
                label: Some("mipmap-bg"),
                layout: &self.bind_group_layout,
                entries: &[wgpu::BindGroupEntry {
                    binding: 0,
                    resource: wgpu::BindingResource::TextureView(&views[level - 1]),
                }],
            });
            let mut pass = encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
                label: Some("mipmap-pass"),
                color_attachments: &[Some(wgpu::RenderPassColorAttachment {
                    view: &views[level],
                    resolve_target: None,
                    ops: wgpu::Operations {
                        load: wgpu::LoadOp::Clear(wgpu::Color::TRANSPARENT),
                        store: wgpu::StoreOp::Store,
                    },
                })],
                depth_stencil_attachment: None,
                timestamp_writes: None,
                occlusion_query_set: None,
            });
            pass.set_pipeline(&self.pipeline);
            pass.set_bind_group(0, &bind_group, &[]);
            pass.draw(0..6, 0..1);
        }
        gpu.queue.submit(Some(encoder.finish()));
    }
}

#[cfg(test)]
mod tests {
    use super::GpuTexture;

    #[test]
    fn mip_counts_reach_one_by_one() {
        assert_eq!(GpuTexture::mip_level_count_for(1, 1), 1);
        assert_eq!(GpuTexture::mip_level_count_for(2, 2), 2);
        assert_eq!(GpuTexture::mip_level_count_for(64, 64), 7);
        assert_eq!(GpuTexture::mip_level_count_for(4096, 2160), 13);
        // Non-power-of-two rounds up to cover the larger dimension.
        assert_eq!(GpuTexture::mip_level_count_for(100, 3), 7);
        // Degenerate input must not underflow.
        assert_eq!(GpuTexture::mip_level_count_for(0, 0), 1);
    }
}
