[package]
name = "selection"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
thiserror.workspace = true
serde.workspace = true
glam.workspace = true
rayon.workspace = true
raster.workspace = true
editor-core.workspace = true
color.workspace = true
